name: 👷 CI/CD (Node.JS)

on:
    workflow_dispatch:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                node: [16.x, 18.x]

        steps:
            - uses: actions/checkout@v3

            - name: Instalar Node.js ${{ matrix.node }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}

            - run: npm ci

            - run: npm test

            - run: npm run build
